// Generated by scripts/workspace-icons/generate.py. Do not edit by hand.

package dev.sk2andy.materialbrowser

import androidx.annotation.DrawableRes
import dev.sk2andy.materialbrowser.shared.ui.WorkspaceIcons

/** Workspace icons as drawables for the home screen widget, which cannot draw Compose vectors. */
internal object WidgetWorkspaceIcons {
    @DrawableRes
    fun forEmoji(emoji: String): Int = when (WorkspaceIcons.idFor(emoji)) {
        "candy" -> R.drawable.ic_widget_workspace_candy
        "work" -> R.drawable.ic_widget_workspace_work
        "shopping" -> R.drawable.ic_widget_workspace_shopping
        "gaming" -> R.drawable.ic_widget_workspace_gaming
        "books" -> R.drawable.ic_widget_workspace_books
        "travel" -> R.drawable.ic_widget_workspace_travel
        "home" -> R.drawable.ic_widget_workspace_home
        "music" -> R.drawable.ic_widget_workspace_music
        "lab" -> R.drawable.ic_widget_workspace_lab
        "news" -> R.drawable.ic_widget_workspace_news
        "heart" -> R.drawable.ic_widget_workspace_heart
        "fire" -> R.drawable.ic_widget_workspace_fire
        "moon" -> R.drawable.ic_widget_workspace_moon
        "nature" -> R.drawable.ic_widget_workspace_nature
        "art" -> R.drawable.ic_widget_workspace_art
        "fitness" -> R.drawable.ic_widget_workspace_fitness
        "idea" -> R.drawable.ic_widget_workspace_idea
        "school" -> R.drawable.ic_widget_workspace_school
        "backpack" -> R.drawable.ic_widget_workspace_backpack
        "writing" -> R.drawable.ic_widget_workspace_writing
        "graduation" -> R.drawable.ic_widget_workspace_graduation
        "reading" -> R.drawable.ic_widget_workspace_reading
        "student" -> R.drawable.ic_widget_workspace_student
        "baby" -> R.drawable.ic_widget_workspace_baby
        "teddy" -> R.drawable.ic_widget_workspace_teddy
        "bottle" -> R.drawable.ic_widget_workspace_bottle
        "family" -> R.drawable.ic_widget_workspace_family
        "ring" -> R.drawable.ic_widget_workspace_ring
        "wedding" -> R.drawable.ic_widget_workspace_wedding
        "money" -> R.drawable.ic_widget_workspace_money
        "card" -> R.drawable.ic_widget_workspace_card
        "coin" -> R.drawable.ic_widget_workspace_coin
        "chart" -> R.drawable.ic_widget_workspace_chart
        "movie" -> R.drawable.ic_widget_workspace_movie
        "popcorn" -> R.drawable.ic_widget_workspace_popcorn
        "television" -> R.drawable.ic_widget_workspace_television
        "camera" -> R.drawable.ic_widget_workspace_camera
        "computer" -> R.drawable.ic_widget_workspace_computer
        "phone" -> R.drawable.ic_widget_workspace_phone
        "car" -> R.drawable.ic_widget_workspace_car
        "bike" -> R.drawable.ic_widget_workspace_bike
        "football" -> R.drawable.ic_widget_workspace_football
        "basketball" -> R.drawable.ic_widget_workspace_basketball
        "beach" -> R.drawable.ic_widget_workspace_beach
        "pizza" -> R.drawable.ic_widget_workspace_pizza
        "coffee" -> R.drawable.ic_widget_workspace_coffee
        "party" -> R.drawable.ic_widget_workspace_party
        "gift" -> R.drawable.ic_widget_workspace_gift
        "dog" -> R.drawable.ic_widget_workspace_dog
        "cat" -> R.drawable.ic_widget_workspace_cat
        "world" -> R.drawable.ic_widget_workspace_world
        "health" -> R.drawable.ic_widget_workspace_health
        "calendar" -> R.drawable.ic_widget_workspace_calendar
        else -> R.drawable.ic_widget_workspace_star
    }
}
