// Generated by scripts/workspace-icons/generate.py. Do not edit by hand.

package dev.sk2andy.materialbrowser

import androidx.annotation.DrawableRes
import androidx.annotation.StringRes
import dev.sk2andy.materialbrowser.shared.ui.WorkspaceIcons

/** Android resources for workspace icons: localized names and home screen widget drawables. */
internal object WorkspaceIconResources {
    /** A drawable for the home screen widget, which cannot draw Compose vectors. */
    @DrawableRes
    fun widgetDrawableFor(emoji: String): Int = when (WorkspaceIcons.idFor(emoji)) {
        "candy" -> R.drawable.ic_widget_workspace_candy
        "work" -> R.drawable.ic_widget_workspace_work
        "shopping" -> R.drawable.ic_widget_workspace_shopping
        "gaming" -> R.drawable.ic_widget_workspace_gaming
        "books" -> R.drawable.ic_widget_workspace_books
        "travel" -> R.drawable.ic_widget_workspace_travel
        "home" -> R.drawable.ic_widget_workspace_home
        "music" -> R.drawable.ic_widget_workspace_music
        "lab" -> R.drawable.ic_widget_workspace_lab
        "news" -> R.drawable.ic_widget_workspace_news
        "heart" -> R.drawable.ic_widget_workspace_heart
        "fire" -> R.drawable.ic_widget_workspace_fire
        "moon" -> R.drawable.ic_widget_workspace_moon
        "nature" -> R.drawable.ic_widget_workspace_nature
        "art" -> R.drawable.ic_widget_workspace_art
        "fitness" -> R.drawable.ic_widget_workspace_fitness
        "idea" -> R.drawable.ic_widget_workspace_idea
        "school" -> R.drawable.ic_widget_workspace_school
        "backpack" -> R.drawable.ic_widget_workspace_backpack
        "writing" -> R.drawable.ic_widget_workspace_writing
        "graduation" -> R.drawable.ic_widget_workspace_graduation
        "reading" -> R.drawable.ic_widget_workspace_reading
        "student" -> R.drawable.ic_widget_workspace_student
        "baby" -> R.drawable.ic_widget_workspace_baby
        "teddy" -> R.drawable.ic_widget_workspace_teddy
        "bottle" -> R.drawable.ic_widget_workspace_bottle
        "family" -> R.drawable.ic_widget_workspace_family
        "ring" -> R.drawable.ic_widget_workspace_ring
        "wedding" -> R.drawable.ic_widget_workspace_wedding
        "money" -> R.drawable.ic_widget_workspace_money
        "card" -> R.drawable.ic_widget_workspace_card
        "coin" -> R.drawable.ic_widget_workspace_coin
        "chart" -> R.drawable.ic_widget_workspace_chart
        "movie" -> R.drawable.ic_widget_workspace_movie
        "popcorn" -> R.drawable.ic_widget_workspace_popcorn
        "television" -> R.drawable.ic_widget_workspace_television
        "camera" -> R.drawable.ic_widget_workspace_camera
        "computer" -> R.drawable.ic_widget_workspace_computer
        "phone" -> R.drawable.ic_widget_workspace_phone
        "car" -> R.drawable.ic_widget_workspace_car
        "bike" -> R.drawable.ic_widget_workspace_bike
        "football" -> R.drawable.ic_widget_workspace_football
        "basketball" -> R.drawable.ic_widget_workspace_basketball
        "beach" -> R.drawable.ic_widget_workspace_beach
        "pizza" -> R.drawable.ic_widget_workspace_pizza
        "coffee" -> R.drawable.ic_widget_workspace_coffee
        "party" -> R.drawable.ic_widget_workspace_party
        "gift" -> R.drawable.ic_widget_workspace_gift
        "dog" -> R.drawable.ic_widget_workspace_dog
        "cat" -> R.drawable.ic_widget_workspace_cat
        "world" -> R.drawable.ic_widget_workspace_world
        "health" -> R.drawable.ic_widget_workspace_health
        "calendar" -> R.drawable.ic_widget_workspace_calendar
        else -> R.drawable.ic_widget_workspace_star
    }

    /** The localized icon name, for accessibility and pickers. */
    @StringRes
    fun nameFor(emoji: String): Int = when (WorkspaceIcons.idFor(emoji)) {
        "candy" -> R.string.workspace_icon_candy
        "work" -> R.string.workspace_icon_work
        "shopping" -> R.string.workspace_icon_shopping
        "gaming" -> R.string.workspace_icon_gaming
        "books" -> R.string.workspace_icon_books
        "travel" -> R.string.workspace_icon_travel
        "home" -> R.string.workspace_icon_home
        "music" -> R.string.workspace_icon_music
        "lab" -> R.string.workspace_icon_lab
        "news" -> R.string.workspace_icon_news
        "heart" -> R.string.workspace_icon_heart
        "fire" -> R.string.workspace_icon_fire
        "moon" -> R.string.workspace_icon_moon
        "nature" -> R.string.workspace_icon_nature
        "art" -> R.string.workspace_icon_art
        "fitness" -> R.string.workspace_icon_fitness
        "idea" -> R.string.workspace_icon_idea
        "school" -> R.string.workspace_icon_school
        "backpack" -> R.string.workspace_icon_backpack
        "writing" -> R.string.workspace_icon_writing
        "graduation" -> R.string.workspace_icon_graduation
        "reading" -> R.string.workspace_icon_reading
        "student" -> R.string.workspace_icon_student
        "baby" -> R.string.workspace_icon_baby
        "teddy" -> R.string.workspace_icon_teddy
        "bottle" -> R.string.workspace_icon_bottle
        "family" -> R.string.workspace_icon_family
        "ring" -> R.string.workspace_icon_ring
        "wedding" -> R.string.workspace_icon_wedding
        "money" -> R.string.workspace_icon_money
        "card" -> R.string.workspace_icon_card
        "coin" -> R.string.workspace_icon_coin
        "chart" -> R.string.workspace_icon_chart
        "movie" -> R.string.workspace_icon_movie
        "popcorn" -> R.string.workspace_icon_popcorn
        "television" -> R.string.workspace_icon_television
        "camera" -> R.string.workspace_icon_camera
        "computer" -> R.string.workspace_icon_computer
        "phone" -> R.string.workspace_icon_phone
        "car" -> R.string.workspace_icon_car
        "bike" -> R.string.workspace_icon_bike
        "football" -> R.string.workspace_icon_football
        "basketball" -> R.string.workspace_icon_basketball
        "beach" -> R.string.workspace_icon_beach
        "pizza" -> R.string.workspace_icon_pizza
        "coffee" -> R.string.workspace_icon_coffee
        "party" -> R.string.workspace_icon_party
        "gift" -> R.string.workspace_icon_gift
        "dog" -> R.string.workspace_icon_dog
        "cat" -> R.string.workspace_icon_cat
        "world" -> R.string.workspace_icon_world
        "health" -> R.string.workspace_icon_health
        "calendar" -> R.string.workspace_icon_calendar
        "puzzle" -> R.string.workspace_icon_puzzle
        "folder" -> R.string.workspace_icon_folder
        "bookmark" -> R.string.workspace_icon_bookmark
        "globe" -> R.string.workspace_icon_globe
        else -> R.string.workspace_icon_star
    }
}
