#!/usr/bin/env python3
"""Generates WorkspaceIcons.kt from Material Symbols Rounded (Apache License 2.0).

Each line of icons.txt maps a workspace icon catalog id (sync/protocol/device-icons-v1.json) to a
Material Symbols name. The script downloads the 24px rounded SVGs and writes their path data, so
the app draws vector icons instead of emoji. The home screen widget cannot draw Compose vectors,
so the script also writes one vector drawable per icon, tinted with the widget colors. Run it after
changing icons.txt:

    python3 scripts/workspace-icons/generate.py
"""

import json
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ICONS = Path(__file__).with_name("icons.txt")
CATALOG = ROOT / "sync/protocol/device-icons-v1.json"
OUTPUT = ROOT / "shared/src/commonMain/kotlin/dev/sk2andy/materialbrowser/shared/ui/WorkspaceIcons.kt"
WIDGET_OUTPUT = ROOT / "app/src/main/java/dev/sk2andy/materialbrowser/WidgetWorkspaceIcons.kt"
DRAWABLES = ROOT / "app/src/main/res/drawable"
URL = (
    "https://raw.githubusercontent.com/google/material-design-icons/master/symbols/web/"
    "{name}/materialsymbolsrounded/{name}_24px.svg"
)


def path_data(name: str) -> str:
    svg = urllib.request.urlopen(URL.format(name=name), timeout=30).read().decode()
    if 'viewBox="0 -960 960 960"' not in svg:
        raise SystemExit(f"{name}: unexpected viewBox")
    paths = re.findall(r'<path d="([^"]+)"', svg)
    if len(paths) != 1:
        raise SystemExit(f"{name}: expected one path, found {len(paths)}")
    return paths[0]


def main() -> None:
    mapping = [line.split() for line in ICONS.read_text().splitlines() if line.strip()]
    catalog = {icon["id"]: icon["emoji"] for icon in json.loads(CATALOG.read_text())["icons"]}
    missing = sorted(set(catalog) - {icon_id for icon_id, _ in mapping})
    if missing:
        raise SystemExit(f"catalog ids without an icon: {missing}")
    data = {icon_id: path_data(name) for icon_id, name in mapping}
    paths = "\n".join(
        f'        "{icon_id}" to "{data[icon_id]}", // {name}' for icon_id, name in mapping
    )
    emoji = "\n".join(f'        "{catalog[icon_id]}" to "{icon_id}",' for icon_id, _ in mapping)
    OUTPUT.write_text(TEMPLATE.format(paths=paths, emoji=emoji))
    for old in DRAWABLES.glob("ic_widget_workspace_*.xml"):
        old.unlink()
    for icon_id, name in mapping:
        drawable = DRAWABLES / f"ic_widget_workspace_{icon_id}.xml"
        drawable.write_text(DRAWABLE_TEMPLATE.format(name=name, path=data[icon_id]))
    resources = "\n".join(
        f'        "{icon_id}" -> R.drawable.ic_widget_workspace_{icon_id}'
        for icon_id, _ in mapping
        if icon_id != "star"
    )
    WIDGET_OUTPUT.write_text(WIDGET_TEMPLATE.format(resources=resources))
    print(f"wrote {OUTPUT.relative_to(ROOT)}, {WIDGET_OUTPUT.relative_to(ROOT)} and {len(mapping)} drawables")


TEMPLATE = """// Generated by scripts/workspace-icons/generate.py from Material Symbols Rounded
// (https://github.com/google/material-design-icons, Apache License 2.0). Do not edit by hand.

package dev.sk2andy.materialbrowser.shared.ui

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.addPathNodes
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.unit.dp

/**
 * Vector icons for workspaces. Workspaces keep an emoji as their stable icon key (it is stored
 * and synced), but Vola never draws emoji: every key maps to a Material Symbol.
 */
object WorkspaceIcons {{
    const val FALLBACK_ID = "star"

    /** Catalog ids in picker order. */
    val ids: List<String> get() = PATHS.keys.toList()

    /** The stored emoji key for a catalog id, used when a workspace picks an icon. */
    fun emojiFor(id: String): String? = EMOJI_TO_ID.entries.firstOrNull {{ it.value == id }}?.key

    /** The catalog id for a stored emoji key; unknown keys get the fallback icon. */
    fun idFor(emoji: String): String = NORMALIZED_TO_ID[normalize(emoji)] ?: FALLBACK_ID

    fun vector(emoji: String): ImageVector = vectorForId(idFor(emoji))

    fun vectorForId(id: String): ImageVector = cache.getOrPut(id) {{
        ImageVector.Builder(
            name = "workspace_$id",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f,
        ).group(translationY = 960f) {{
            addPath(
                pathData = addPathNodes(PATHS[id] ?: PATHS.getValue(FALLBACK_ID)),
                fill = SolidColor(Color.Black),
            )
        }}.build()
    }}

    private val cache = mutableMapOf<String, ImageVector>()

    private val PATHS: Map<String, String> = linkedMapOf(
{paths}
    )

    private val EMOJI_TO_ID: Map<String, String> = mapOf(
{emoji}
    )

    private val NORMALIZED_TO_ID: Map<String, String> =
        EMOJI_TO_ID.entries.associate {{ (emoji, id) -> normalize(emoji) to id }}

    /** Ignores surrounding spaces and emoji presentation selectors, which keyboards add or drop. */
    private fun normalize(emoji: String): String = emoji.trim().replace("\\uFE0F", "")
}}
"""

DRAWABLE_TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/workspace-icons/generate.py: Material Symbols Rounded "{name}"
     (Apache License 2.0). Do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="960"
    android:viewportHeight="960">
    <group android:translateY="960">
        <path
            android:fillColor="@color/candy_widget_on_surface"
            android:pathData="{path}" />
    </group>
</vector>
"""

WIDGET_TEMPLATE = """// Generated by scripts/workspace-icons/generate.py. Do not edit by hand.

package dev.sk2andy.materialbrowser

import androidx.annotation.DrawableRes
import dev.sk2andy.materialbrowser.shared.ui.WorkspaceIcons

/** Workspace icons as drawables for the home screen widget, which cannot draw Compose vectors. */
internal object WidgetWorkspaceIcons {{
    @DrawableRes
    fun forEmoji(emoji: String): Int = when (WorkspaceIcons.idFor(emoji)) {{
{resources}
        else -> R.drawable.ic_widget_workspace_star
    }}
}}
"""


if __name__ == "__main__":
    main()
