#!/usr/bin/env python3
"""Machine checks for the quality bar in docs/vola/ROADMAP.md, section 4.

Usage:
  quality_gates.py size [--update]   the largest legacy files must not grow (tech-plan.md, section 1)
  quality_gates.py tokens --base REV  lines added since REV use ui/theme tokens, not literals
  quality_gates.py engine             GeckoView and WebView types stay inside the engine adapters
  quality_gates.py brand              no "Candy" in strings the user can see

Findings are printed as GitHub Actions annotations; any finding exits with status 1.
"""

import argparse
import json
import re
import subprocess
import sys
import xml.etree.ElementTree as ElementTree
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
SIZE_BASELINE = Path(__file__).resolve().parent / "size-baseline.json"
SOURCE_ROOTS = ("app/src/main/java/", "shared/src/commonMain/", "shared/src/androidMain/")
STRINGS_GLOB = "app/src/main/res/values*/strings.xml"

# Engine types belong to the adapters (CLAUDE.md rule 1). userscript injects scripts into WebView
# pages and is part of the WebView adapter.
ENGINE_ADAPTER_DIRS = ("/browser/gecko/", "/browser/systemwebview/", "/browser/userscript/")
ENGINE_REFERENCE = re.compile(r"\b(org\.mozilla\.geckoview|android\.webkit)\.")

# Where literals are the point: the token definitions, generated sources and previews.
TOKEN_EXEMPT_DIRS = ("/ui/theme/", "/ui/icons/")
TOKEN_EXEMPT_SUFFIXES = ("Preview.kt", "Previews.kt")
GENERATED_MARKER = re.compile(r"generated by|do not edit", re.IGNORECASE)
TOKEN_EXEMPT_COMMENT = "token-exempt:"
TOKEN_RULES = (
    (re.compile(r"\bColor\(0x[0-9A-Fa-f]+"), "a literal color; use a ui/theme color role"),
    (
        re.compile(r"\bColor\.(Black|White|Red|Green|Blue|Gray|DarkGray|LightGray|Yellow|Cyan|Magenta)\b"),
        "a named color; use a ui/theme color role",
    ),
    (re.compile(r"\btween\s*(<[^>]*>)?\s*\([^)]*\d"), "a tween with literal timing; use VolaMotion"),
    (re.compile(r"\bspring\s*(<[^>]*>)?\s*\([^)]*\d"), "a spring with literal values; use VolaMotion"),
    (re.compile(r"\bdurationMillis\s*=\s*\d"), "a literal duration; use VolaMotion"),
)
DIMENSION = re.compile(r"(?<![\w.])(\d+(?:\.\d+)?)f?\.(dp|sp)\b")


def relative(path):
    return Path(path).resolve().relative_to(ROOT).as_posix()


def annotate(path, line, message):
    location = f"file={path},line={line}" if line else f"file={path}"
    print(f"::error {location}::{message}")


def code_part(line):
    """The line without a trailing // comment; comment-only and KDoc lines have no code."""
    stripped = line.strip()
    if stripped.startswith(("//", "*", "/*")):
        return ""
    return re.sub(r"\s//.*$", "", line)


# size

def line_count(path):
    with open(path, encoding="utf-8") as handle:
        return sum(1 for _ in handle)


def size_findings(baseline, count=line_count):
    findings = []
    for path, limit in sorted(baseline.items()):
        lines = count(ROOT / path)
        if lines > limit:
            findings.append((path, f"grew from {limit} to {lines} lines; move new code into a feature "
                                   "controller (docs/vola/tech-plan.md, section 1)"))
        elif lines < limit:
            findings.append((path, f"shrank from {limit} to {lines} lines; lock it in with "
                                   "`scripts/ci/quality_gates.py size --update`"))
    return findings


def check_size(update):
    baseline = json.loads(SIZE_BASELINE.read_text(encoding="utf-8"))
    if update:
        updated = {path: line_count(ROOT / path) for path in baseline}
        SIZE_BASELINE.write_text(json.dumps(updated, indent=2) + "\n", encoding="utf-8")
        return []
    return size_findings(baseline)


# tokens

def added_lines(diff_text):
    """(path, line number, text) for every line a unified diff with --unified=0 adds."""
    path, number = None, 0
    for raw in diff_text.splitlines():
        if raw.startswith("+++ "):
            target = raw[4:]
            path = None if target == "/dev/null" else target[2:] if target.startswith("b/") else target
        elif raw.startswith("@@"):
            match = re.search(r"\+(\d+)", raw)
            number = int(match.group(1)) if match else 0
        elif raw.startswith("+") and path:
            yield path, number, raw[1:]
            number += 1


def token_scope(path, head=""):
    if not path.endswith(".kt") or not path.startswith(SOURCE_ROOTS):
        return False
    if any(part in f"/{path}" for part in TOKEN_EXEMPT_DIRS) or path.endswith(TOKEN_EXEMPT_SUFFIXES):
        return False
    return not GENERATED_MARKER.search(head)


def token_findings_in_line(text):
    if TOKEN_EXEMPT_COMMENT in text:
        return []
    code = code_part(text)
    findings = [message for pattern, message in TOKEN_RULES if pattern.search(code)]
    for match in DIMENSION.finditer(code):
        if float(match.group(1)) != 0:
            findings.append(f"a literal {match.group(0)}; use VolaSpacing, VolaShapes or a ui/theme token")
    return findings


def check_tokens(base):
    diff = subprocess.run(
        ["git", "diff", "--unified=0", "--diff-filter=AM", base, "HEAD", "--", "*.kt"],
        cwd=ROOT, check=True, capture_output=True, text=True,
    ).stdout
    heads = {}
    findings = []
    for path, number, text in added_lines(diff):
        if path not in heads:
            file = ROOT / path
            heads[path] = file.read_text(encoding="utf-8")[:600] if file.exists() else ""
        if not token_scope(path, heads[path]):
            continue
        for message in token_findings_in_line(text):
            findings.append((path, number, f"{message} (or add `// {TOKEN_EXEMPT_COMMENT} reason`)"))
    return findings


# engine

def engine_findings(files):
    findings = []
    for path in files:
        posix = f"/{relative(path)}"
        if any(part in posix for part in ENGINE_ADAPTER_DIRS):
            continue
        for number, line in enumerate(Path(path).read_text(encoding="utf-8").splitlines(), start=1):
            if ENGINE_REFERENCE.search(code_part(line)):
                findings.append((relative(path), number, "an engine type outside the engine adapters; "
                                 "add a port and implement it in browser/gecko and browser/systemwebview"))
    return findings


def source_files():
    for root in SOURCE_ROOTS:
        yield from sorted((ROOT / root).rglob("*.kt"))


# brand

def brand_findings_in_xml(xml_text):
    root = ElementTree.fromstring(xml_text)
    findings = []
    for node in root.iter():
        if node.tag in ("string", "item"):
            text = "".join(node.itertext())
            if re.search(r"\bCandy\b", text):
                findings.append(node.get("name") or text.strip())
    return findings


def check_brand():
    findings = []
    for path in sorted(ROOT.glob(STRINGS_GLOB)):
        for name in brand_findings_in_xml(path.read_text(encoding="utf-8")):
            findings.append((relative(path), 0, f"\"{name}\" shows the Candy brand; Vola's UI never does "
                                                "(CLAUDE.md rule 7)"))
    return findings


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    commands = parser.add_subparsers(dest="command", required=True)
    commands.add_parser("size").add_argument("--update", action="store_true")
    commands.add_parser("tokens").add_argument("--base", required=True)
    commands.add_parser("engine")
    commands.add_parser("brand")
    args = parser.parse_args(argv)

    if args.command == "size":
        findings = [(path, 0, message) for path, message in check_size(args.update)]
    elif args.command == "tokens":
        findings = check_tokens(args.base)
    elif args.command == "engine":
        findings = engine_findings(source_files())
    else:
        findings = check_brand()

    for path, line, message in findings:
        annotate(path, line, message)
    print(f"{args.command}: {len(findings)} finding(s)")
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
