#!/usr/bin/env python3
"""Machine checks for the quality bar in docs/vola/ROADMAP.md, section 4.

Usage:
  quality_gates.py size [--update]   the largest legacy files must not grow (tech-plan.md, section 1)
  quality_gates.py tokens --base REV  lines added since REV use ui/theme tokens, not literals
  quality_gates.py engine             GeckoView and WebView types stay inside the engine adapters
  quality_gates.py brand              no "Candy" in strings the user can see
  quality_gates.py semantics          clearAndSetSemantics is never toggled and never hides a later testTag

Findings are printed as GitHub Actions annotations; any finding exits with status 1.
"""

import argparse
import json
import re
import subprocess
import sys
import xml.etree.ElementTree as ElementTree
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
SIZE_BASELINE = Path(__file__).resolve().parent / "size-baseline.json"
SOURCE_ROOTS = ("app/src/main/java/", "shared/src/commonMain/", "shared/src/androidMain/")
STRINGS_GLOB = "app/src/main/res/values*/strings.xml"

# Engine types belong to the adapters (CLAUDE.md rule 1). userscript injects scripts into WebView
# pages and is part of the WebView adapter.
ENGINE_ADAPTER_DIRS = ("/browser/gecko/", "/browser/systemwebview/", "/browser/userscript/")
ENGINE_REFERENCE = re.compile(r"\b(org\.mozilla\.geckoview|android\.webkit)\.")

# Where literals are the point: the token definitions, generated sources and previews.
TOKEN_EXEMPT_DIRS = ("/ui/theme/", "/ui/icons/")
TOKEN_EXEMPT_SUFFIXES = ("Preview.kt", "Previews.kt")
GENERATED_MARKER = re.compile(r"generated by|do not edit", re.IGNORECASE)
TOKEN_EXEMPT_COMMENT = "token-exempt:"
TOKEN_RULES = (
    (re.compile(r"\bColor\(0x[0-9A-Fa-f]+"), "a literal color; use a ui/theme color role"),
    (
        re.compile(r"\bColor\.(Black|White|Red|Green|Blue|Gray|DarkGray|LightGray|Yellow|Cyan|Magenta)\b"),
        "a named color; use a ui/theme color role",
    ),
    (re.compile(r"\btween\s*(<[^>]*>)?\s*\([^)]*\d"), "a tween with literal timing; use VolaMotion"),
    (re.compile(r"\bspring\s*(<[^>]*>)?\s*\([^)]*\d"), "a spring with literal values; use VolaMotion"),
    (re.compile(r"\bdurationMillis\s*=\s*\d"), "a literal duration; use VolaMotion"),
)
DIMENSION = re.compile(r"(?<![\w.])(\d+(?:\.\d+)?)f?\.(dp|sp)\b")


def relative(path):
    return Path(path).resolve().relative_to(ROOT).as_posix()


def annotate(path, line, message):
    location = f"file={path},line={line}" if line else f"file={path}"
    print(f"::error {location}::{message}")


def code_part(line):
    """The line without a trailing // comment; comment-only and KDoc lines have no code."""
    stripped = line.strip()
    if stripped.startswith(("//", "*", "/*")):
        return ""
    return re.sub(r"\s//.*$", "", line)


# size

def line_count(path):
    with open(path, encoding="utf-8") as handle:
        return sum(1 for _ in handle)


def size_findings(baseline, count=line_count):
    findings = []
    for path, limit in sorted(baseline.items()):
        lines = count(ROOT / path)
        if lines > limit:
            findings.append((path, f"grew from {limit} to {lines} lines; move new code into a feature "
                                   "controller (docs/vola/tech-plan.md, section 1)"))
        elif lines < limit:
            findings.append((path, f"shrank from {limit} to {lines} lines; lock it in with "
                                   "`scripts/ci/quality_gates.py size --update`"))
    return findings


def check_size(update):
    baseline = json.loads(SIZE_BASELINE.read_text(encoding="utf-8"))
    if update:
        updated = {path: line_count(ROOT / path) for path in baseline}
        SIZE_BASELINE.write_text(json.dumps(updated, indent=2) + "\n", encoding="utf-8")
        return []
    return size_findings(baseline)


# tokens

def added_lines(diff_text):
    """(path, line number, text) for every line a unified diff with --unified=0 adds."""
    path, number = None, 0
    for raw in diff_text.splitlines():
        if raw.startswith("+++ "):
            target = raw[4:]
            path = None if target == "/dev/null" else target[2:] if target.startswith("b/") else target
        elif raw.startswith("@@"):
            match = re.search(r"\+(\d+)", raw)
            number = int(match.group(1)) if match else 0
        elif raw.startswith("+") and path:
            yield path, number, raw[1:]
            number += 1


def token_scope(path, head=""):
    if not path.endswith(".kt") or not path.startswith(SOURCE_ROOTS):
        return False
    if any(part in f"/{path}" for part in TOKEN_EXEMPT_DIRS) or path.endswith(TOKEN_EXEMPT_SUFFIXES):
        return False
    return not GENERATED_MARKER.search(head)


def token_findings_in_line(text):
    if TOKEN_EXEMPT_COMMENT in text:
        return []
    code = code_part(text)
    findings = [message for pattern, message in TOKEN_RULES if pattern.search(code)]
    for match in DIMENSION.finditer(code):
        if float(match.group(1)) != 0:
            findings.append(f"a literal {match.group(0)}; use VolaSpacing, VolaShapes or a ui/theme token")
    return findings


def check_tokens(base):
    diff = subprocess.run(
        ["git", "diff", "--unified=0", "--diff-filter=AM", base, "HEAD", "--", "*.kt"],
        cwd=ROOT, check=True, capture_output=True, text=True,
    ).stdout
    heads = {}
    findings = []
    for path, number, text in added_lines(diff):
        if path not in heads:
            file = ROOT / path
            heads[path] = file.read_text(encoding="utf-8")[:600] if file.exists() else ""
        if not token_scope(path, heads[path]):
            continue
        for message in token_findings_in_line(text):
            findings.append((path, number, f"{message} (or add `// {TOKEN_EXEMPT_COMMENT} reason`)"))
    return findings


# engine

def engine_findings(files):
    findings = []
    for path in files:
        posix = f"/{relative(path)}"
        if any(part in posix for part in ENGINE_ADAPTER_DIRS):
            continue
        for number, line in enumerate(Path(path).read_text(encoding="utf-8").splitlines(), start=1):
            if ENGINE_REFERENCE.search(code_part(line)):
                findings.append((relative(path), number, "an engine type outside the engine adapters; "
                                 "add a port and implement it in browser/gecko and browser/systemwebview"))
    return findings


def source_files():
    for root in SOURCE_ROOTS:
        yield from sorted((ROOT / root).rglob("*.kt"))


# semantics

SEMANTICS_EXEMPT_COMMENT = "semantics-exempt:"
CLEAR_SEMANTICS = "clearAndSetSemantics"
OPENERS = {"(": ")", "{": "}", "[": "]"}
CLOSERS = {value: key for key, value in OPENERS.items()}


def kotlin_code(text):
    """[text] with comments, strings and char literals blanked out; offsets and newlines kept."""
    out = list(text)
    i, n = 0, len(text)

    def blank(start, end):
        for k in range(start, min(end, n)):
            if out[k] != "\n":
                out[k] = " "

    while i < n:
        if text.startswith("//", i):
            end = text.find("\n", i)
            end = n if end < 0 else end
            blank(i, end)
            i = end
        elif text.startswith("/*", i):
            depth, j = 1, i + 2
            while j < n and depth:
                if text.startswith("/*", j):
                    depth, j = depth + 1, j + 2
                elif text.startswith("*/", j):
                    depth, j = depth - 1, j + 2
                else:
                    j += 1
            blank(i, j)
            i = j
        elif text.startswith('"""', i):
            end = text.find('"""', i + 3)
            end = n if end < 0 else end + 3
            blank(i, end)
            i = end
        elif text[i] in "\"'":
            quote, j = text[i], i + 1
            while j < n and text[j] != quote and text[j] != "\n":
                j += 2 if text[j] == "\\" else 1
            blank(i, j + 1)
            i = j + 1
        else:
            i += 1
    return "".join(out)


def matching_close(code, start):
    """The index after the bracket that closes the one at [start]."""
    depth = 0
    for i in range(start, len(code)):
        if code[i] in OPENERS:
            depth += 1
        elif code[i] in CLOSERS:
            depth -= 1
            if depth == 0:
                return i + 1
    return len(code)


def matching_open(code, end):
    """The index of the bracket that opens the one closing at [end]."""
    depth = 0
    for i in range(end, -1, -1):
        if code[i] in CLOSERS:
            depth += 1
        elif code[i] in OPENERS:
            depth -= 1
            if depth == 0:
                return i
    return 0


def enclosing_open(code, position):
    """The unmatched bracket around [position], or -1 at the top level."""
    depth = 0
    for i in range(position - 1, -1, -1):
        if code[i] in CLOSERS:
            depth += 1
        elif code[i] in OPENERS:
            if depth == 0:
                return i
            depth -= 1
    return -1


def word_before(code, position):
    i = position - 1
    while i >= 0 and code[i].isspace():
        i -= 1
    end = i + 1
    while i >= 0 and (code[i].isalnum() or code[i] == "_"):
        i -= 1
    return code[i + 1:end], i + 1


def depth_zero(text):
    """[text] with the contents of its bracket pairs removed."""
    out, depth = [], 0
    for char in text:
        if char in OPENERS:
            depth += 1
        elif char in CLOSERS:
            depth = max(depth - 1, 0)
        elif depth == 0:
            out.append(char)
    return "".join(out)


def governing_if(code, position):
    """The `if` whose branch holds [position], or None when no condition picks it."""
    opener = enclosing_open(code, position)
    start = opener + 1
    if opener >= 0 and code[opener] == "{":
        word, at = word_before(code, opener)
        if word == "else":
            return if_before_else(code, at)
        if word == "" and at > 0 and code[at - 1] == ")":
            paren = matching_open(code, at - 1)
            word, if_at = word_before(code, paren)
            if word == "if":
                return if_at
    segment = code[start:position]
    # Only the expression that holds [position]: after the last argument or statement break.
    cut = max(segment.rfind(","), segment.rfind(";"), statement_break(segment))
    flat = depth_zero(segment[cut + 1:])
    if not re.search(r"\b(if|else|when)\b", flat):
        return None
    for match in reversed(list(re.finditer(r"\bif\b", code[start + cut + 1:position]))):
        at = start + cut + 1 + match.start()
        if enclosing_open(code, at) == opener:
            return at
    return -1  # a `when` branch or an `else` without its `if` in sight


def statement_break(segment):
    """The last newline in [segment] that ends a statement at its own bracket depth."""
    depth = 0
    for i in range(len(segment) - 1, -1, -1):
        char = segment[i]
        if char in CLOSERS:
            depth += 1
        elif char in OPENERS:
            depth -= 1
        elif char == "\n" and depth == 0:
            before = segment[:i].rstrip()
            after = segment[i + 1:].lstrip()
            if before and before[-1] not in "=(,{+-*/&|?:" and not before.endswith("else") \
                    and not after.startswith((".", "?.", "else")):
                return i
    return -1


def if_before_else(code, else_at):
    i = else_at - 1
    while i >= 0 and code[i].isspace():
        i -= 1
    if i >= 0 and code[i] == "}":
        i = matching_open(code, i) - 1
        while i >= 0 and code[i].isspace():
            i -= 1
    if i >= 0 and code[i] == ")":
        word, at = word_before(code, matching_open(code, i))
        return at if word == "if" else -1
    return -1


def if_branches(code, if_at):
    """The branch texts of the if-else chain starting at [if_at]."""
    branches = []
    i = if_at
    while True:
        i = code.index("(", i)
        i = skip_space(code, matching_close(code, i))
        end = branch_end(code, i)
        branches.append(code[i:end])
        j = skip_space(code, end)
        if not code.startswith("else", j) or (j + 4 < len(code) and (code[j + 4].isalnum() or code[j + 4] == "_")):
            return branches
        j = skip_space(code, j + 4)
        if code.startswith("if", j) and not (code[j + 2].isalnum() or code[j + 2] == "_"):
            i = j
            continue
        branches.append(code[j:branch_end(code, j)])
        return branches


def skip_space(code, i):
    while i < len(code) and code[i].isspace():
        i += 1
    return i


def branch_end(code, i):
    if i < len(code) and code[i] == "{":
        return matching_close(code, i)
    j = i
    while j < len(code):
        char = code[j]
        if char in OPENERS:
            j = matching_close(code, j)
            continue
        if char in ",;" or char in CLOSERS:
            return j
        if code.startswith("else", j) and not code[j - 1].isalnum() \
                and (j + 4 >= len(code) or not code[j + 4].isalnum()):
            return j
        if char == "\n" and not code[j + 1:].lstrip().startswith((".", "?.", "else")):
            return j
        j += 1
    return j


def hidden_test_tags(code, position):
    """Offsets of `.testTag` calls later in the chain that starts clearing at [position]."""
    found = []
    i = skip_space(code, position + len(CLEAR_SEMANTICS))
    while True:
        while i < len(code) and code[i] in "({":
            i = skip_space(code, matching_close(code, i))
        if i < len(code) and code[i] == ")":
            # The end of a `.then(...)` argument: the outer chain goes on after it.
            word, _ = word_before(code, matching_open(code, i))
            if word != "then":
                return found
            i = skip_space(code, i + 1)
            continue
        if not code.startswith(".", i):
            return found
        match = re.match(r"\.\s*(\w+)", code[i:])
        if match is None:
            return found
        if match.group(1) == "testTag":
            found.append(i)
        i = skip_space(code, i + match.end())


def semantics_findings_in_text(text, path):
    code = kotlin_code(text)
    lines = text.splitlines()
    findings = []

    def line_of(offset):
        return code.count("\n", 0, offset) + 1

    def exempt(number):
        nearby = lines[max(number - 2, 0):number]
        return any(SEMANTICS_EXEMPT_COMMENT in line for line in nearby)

    for match in re.finditer(rf"\b{CLEAR_SEMANTICS}\b", code):
        position = match.start()
        if code[match.end():].lstrip()[:1] not in ("{", "("):
            continue  # an import or a reference, not a call
        number = line_of(position)
        if exempt(number):
            continue
        if_at = governing_if(code, position)
        if if_at is not None and (if_at < 0 or not all(
            CLEAR_SEMANTICS in branch for branch in if_branches(code, if_at)
        )):
            findings.append((path, number, f"{CLEAR_SEMANTICS} switched on and off by a condition "
                             "replaces the semantics node; use Modifier.clearSemanticsWhen(...) "
                             "(ui/ModalSemantics.kt)"))
        for tag in hidden_test_tags(code, position):
            findings.append((path, line_of(tag), f"testTag after {CLEAR_SEMANTICS} in the same chain is "
                             "cleared with the rest; put it before"))
    return findings


def semantics_findings(files):
    findings = []
    for path in files:
        findings += semantics_findings_in_text(Path(path).read_text(encoding="utf-8"), relative(path))
    return findings


# brand

def brand_findings_in_xml(xml_text):
    root = ElementTree.fromstring(xml_text)
    findings = []
    for node in root.iter():
        if node.tag in ("string", "item"):
            text = "".join(node.itertext())
            if re.search(r"\bCandy\b", text):
                findings.append(node.get("name") or text.strip())
    return findings


def check_brand():
    findings = []
    for path in sorted(ROOT.glob(STRINGS_GLOB)):
        for name in brand_findings_in_xml(path.read_text(encoding="utf-8")):
            findings.append((relative(path), 0, f"\"{name}\" shows the Candy brand; Vola's UI never does "
                                                "(CLAUDE.md rule 7)"))
    return findings


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    commands = parser.add_subparsers(dest="command", required=True)
    commands.add_parser("size").add_argument("--update", action="store_true")
    commands.add_parser("tokens").add_argument("--base", required=True)
    commands.add_parser("engine")
    commands.add_parser("brand")
    commands.add_parser("semantics")
    args = parser.parse_args(argv)

    if args.command == "size":
        findings = [(path, 0, message) for path, message in check_size(args.update)]
    elif args.command == "tokens":
        findings = check_tokens(args.base)
    elif args.command == "engine":
        findings = engine_findings(source_files())
    elif args.command == "semantics":
        findings = semantics_findings(source_files())
    else:
        findings = check_brand()

    for path, line, message in findings:
        annotate(path, line, message)
    print(f"{args.command}: {len(findings)} finding(s)")
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
