package dev.sk2andy.materialbrowser.shared.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/*
 * Vola's own palette: a tonal-spot scheme generated with Material Color Utilities from the brand
 * violet (#6D4CFF, hue 293, primary chroma 56) with the brand cyan (#22D3EE, hue 213) as the
 * tertiary accent and violet-tinted neutrals. Every role is set explicitly so the scheme does not
 * fall back to the Material baseline purple for roles like outline or error.
 */
val VolaLightColors = lightColorScheme(
    primary = Color(0xFF5E4EB7),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFE5DEFF),
    onPrimaryContainer = Color(0xFF46349E),
    inversePrimary = Color(0xFFC9BFFF),
    secondary = Color(0xFF5F5C71),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFE5DFF9),
    onSecondaryContainer = Color(0xFF484459),
    tertiary = Color(0xFF006877),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFA2EEFF),
    onTertiaryContainer = Color(0xFF004E5A),
    background = Color(0xFFFDF8FE),
    onBackground = Color(0xFF1C1B1F),
    surface = Color(0xFFFDF8FE),
    onSurface = Color(0xFF1C1B1F),
    surfaceVariant = Color(0xFFE5E0ED),
    onSurfaceVariant = Color(0xFF484550),
    surfaceTint = Color(0xFF5E4EB7),
    inverseSurface = Color(0xFF313035),
    inverseOnSurface = Color(0xFFF4EFF6),
    error = Color(0xFFBA1A1A),
    onError = Color.White,
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    outline = Color(0xFF797581),
    outlineVariant = Color(0xFFC9C4D1),
    scrim = Color.Black,
    surfaceBright = Color(0xFFFDF8FE),
    surfaceDim = Color(0xFFDDD8DF),
    surfaceContainerLowest = Color.White,
    surfaceContainerLow = Color(0xFFF7F2F8),
    surfaceContainer = Color(0xFFF1ECF3),
    surfaceContainerHigh = Color(0xFFEBE7ED),
    surfaceContainerHighest = Color(0xFFE5E1E7),
)

val VolaDarkColors = darkColorScheme(
    primary = Color(0xFFC9BFFF),
    onPrimary = Color(0xFF2F1887),
    primaryContainer = Color(0xFF46349E),
    onPrimaryContainer = Color(0xFFE5DEFF),
    inversePrimary = Color(0xFF5E4EB7),
    secondary = Color(0xFFC9C3DC),
    onSecondary = Color(0xFF312E41),
    secondaryContainer = Color(0xFF484459),
    onSecondaryContainer = Color(0xFFE5DFF9),
    tertiary = Color(0xFF75D4E7),
    onTertiary = Color(0xFF00363E),
    tertiaryContainer = Color(0xFF004E5A),
    onTertiaryContainer = Color(0xFFA2EEFF),
    background = Color(0xFF141317),
    onBackground = Color(0xFFE5E1E7),
    surface = Color(0xFF141317),
    onSurface = Color(0xFFE5E1E7),
    surfaceVariant = Color(0xFF484550),
    onSurfaceVariant = Color(0xFFC9C4D1),
    surfaceTint = Color(0xFFC9BFFF),
    inverseSurface = Color(0xFFE5E1E7),
    inverseOnSurface = Color(0xFF313035),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF938F9B),
    outlineVariant = Color(0xFF484550),
    scrim = Color.Black,
    surfaceBright = Color(0xFF3A383D),
    surfaceDim = Color(0xFF141317),
    surfaceContainerLowest = Color(0xFF0E0E12),
    surfaceContainerLow = Color(0xFF1C1B1F),
    surfaceContainer = Color(0xFF201F24),
    surfaceContainerHigh = Color(0xFF2B292E),
    surfaceContainerHighest = Color(0xFF353439),
)

val NeutralLightColors = lightColorScheme(
    primary = Color(0xFF4D5D62),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFD0E6EC),
    onPrimaryContainer = Color(0xFF081F24),
    secondary = Color(0xFF586064),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFDCE4E7),
    onSecondaryContainer = Color(0xFF171C1E),
    tertiary = Color(0xFF5D5F6B),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFE1E2EF),
    onTertiaryContainer = Color(0xFF191A24),
    surface = Color(0xFFFAF9F7),
    surfaceDim = Color(0xFFDBDAD8),
    surfaceBright = Color(0xFFFAF9F7),
    surfaceContainerLowest = Color.White,
    surfaceContainerLow = Color(0xFFF5F4F2),
    surfaceContainer = Color(0xFFEFEEEC),
    surfaceContainerHigh = Color(0xFFE9E8E6),
    surfaceContainerHighest = Color(0xFFE3E2E0),
    surfaceVariant = Color(0xFFDFE3E4),
    onSurfaceVariant = Color(0xFF41484B),
    outline = Color(0xFF71787B),
    outlineVariant = Color(0xFFC1C7C9),
    inverseSurface = Color(0xFF303132),
    inverseOnSurface = Color(0xFFF1F0EE),
    inversePrimary = Color(0xFFB4CBD1),
)

val NeutralDarkColors = darkColorScheme(
    primary = Color(0xFFB4CBD1),
    onPrimary = Color(0xFF1F3439),
    primaryContainer = Color(0xFF354A4F),
    onPrimaryContainer = Color(0xFFD0E6EC),
    secondary = Color(0xFFC0C8CB),
    onSecondary = Color(0xFF2A3134),
    secondaryContainer = Color(0xFF41484B),
    onSecondaryContainer = Color(0xFFDCE4E7),
    tertiary = Color(0xFFC5C6D4),
    onTertiary = Color(0xFF2E303B),
    tertiaryContainer = Color(0xFF454751),
    onTertiaryContainer = Color(0xFFE1E2EF),
    surface = Color(0xFF121415),
    surfaceDim = Color(0xFF121415),
    surfaceBright = Color(0xFF383A3B),
    surfaceContainerLowest = Color(0xFF0D0F10),
    surfaceContainerLow = Color(0xFF1A1C1D),
    surfaceContainer = Color(0xFF1E2021),
    surfaceContainerHigh = Color(0xFF292A2B),
    surfaceContainerHighest = Color(0xFF343536),
    surfaceVariant = Color(0xFF41484B),
    onSurfaceVariant = Color(0xFFC1C7C9),
    outline = Color(0xFF8B9295),
    outlineVariant = Color(0xFF41484B),
    inverseSurface = Color(0xFFE3E2E0),
    inverseOnSurface = Color(0xFF2F3031),
    inversePrimary = Color(0xFF4D5D62),
)
