#!/usr/bin/env python3
"""Tests for ci/quality_gates.py: size ratchet, token rules, engine boundary, brand and semantics checks."""

import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "ci"))
import quality_gates as gates  # noqa: E402

UI = "app/src/main/java/dev/sk2andy/materialbrowser/ui/FindInPageBar.kt"
DIFF = f"""diff --git a/{UI} b/{UI}
--- a/{UI}
+++ b/{UI}
@@ -10,0 +11,2 @@ fun FindInPageBar() {{
+    val height = 52.dp
+    val gap = VolaSpacing.small
@@ -40 +42 @@
-    old()
+    new()
diff --git a/gone.kt b/gone.kt
--- a/gone.kt
+++ /dev/null
"""


class SizeTest(unittest.TestCase):
    def test_growth_and_shrink_are_findings_equal_is_not(self):
        sizes = {"a.kt": 10, "b.kt": 12, "c.kt": 8}
        findings = gates.size_findings({"a.kt": 10, "b.kt": 10, "c.kt": 10}, lambda path: sizes[path.name])
        self.assertEqual([path for path, _ in findings], ["b.kt", "c.kt"])
        self.assertIn("grew from 10 to 12", findings[0][1])
        self.assertIn("--update", findings[1][1])

    def test_repository_baseline_matches_the_tree(self):
        self.assertEqual(gates.check_size(update=False), [])


class AddedLinesTest(unittest.TestCase):
    def test_reports_added_lines_with_their_new_line_numbers(self):
        self.assertEqual(
            list(gates.added_lines(DIFF)),
            [(UI, 11, "    val height = 52.dp"), (UI, 12, "    val gap = VolaSpacing.small"), (UI, 42, "    new()")],
        )


class TokenRulesTest(unittest.TestCase):
    def assertFinding(self, line):
        self.assertTrue(gates.token_findings_in_line(line), line)

    def assertClean(self, line):
        self.assertEqual(gates.token_findings_in_line(line), [], line)

    def test_literals_are_findings(self):
        for line in [
            "Modifier.padding(16.dp)",
            "fontSize = 14.sp",
            "val corner = 2.5.dp",
            "color = Color(0xFF6750A4)",
            "tint = Color.White",
            "animationSpec = tween(durationMillis = 200)",
            "animationSpec = tween<Float>(300)",
            "spring(dampingRatio = 0.8f, stiffness = 400f)",
        ]:
            with self.subTest(line=line):
                self.assertFinding(line)

    def test_tokens_zero_and_comments_are_clean(self):
        for line in [
            "Modifier.padding(VolaSpacing.medium)",
            "val none = 0.dp",
            "color = Color.Transparent",
            "animationSpec = VolaMotion.standard()",
            "spring(dampingRatio = Spring.DampingRatioNoBouncy)",
            "// The board uses 16.dp here.",
            " * KDoc that mentions 24.dp.",
            "Modifier.padding(16.dp) // token-exempt: matches the system gesture inset",
            "val v = item.size.dp",
        ]:
            with self.subTest(line=line):
                self.assertClean(line)

    def test_scope_skips_theme_icons_previews_tests_and_generated_files(self):
        self.assertTrue(gates.token_scope(UI))
        for path in [
            "app/src/main/java/dev/sk2andy/materialbrowser/ui/theme/VolaTokens.kt",
            "shared/src/commonMain/kotlin/dev/sk2andy/materialbrowser/shared/ui/icons/VolaIcons.kt",
            "app/src/main/java/dev/sk2andy/materialbrowser/ui/BrowserContentFramePreviews.kt",
            "app/src/test/java/dev/sk2andy/materialbrowser/ui/FooTest.kt",
            "scripts/tool.py",
        ]:
            with self.subTest(path=path):
                self.assertFalse(gates.token_scope(path))
        self.assertFalse(gates.token_scope(UI, "// Generated by scripts/workspace-icons/generate.py"))


class EngineBoundaryTest(unittest.TestCase):
    def test_engine_types_only_inside_adapters(self):
        with tempfile.TemporaryDirectory(dir=gates.ROOT) as temp:
            base = Path(temp)
            adapter = base / "browser/gecko/Adapter.kt"
            ui = base / "ui/Screen.kt"
            comment = base / "ui/Notes.kt"
            for path in (adapter, ui, comment):
                path.parent.mkdir(parents=True, exist_ok=True)
            adapter.write_text("import org.mozilla.geckoview.GeckoSession\n", encoding="utf-8")
            ui.write_text("val a = 1\nval v = android.webkit.WebView(context)\n", encoding="utf-8")
            comment.write_text("// android.webkit.WebView is wrapped by the adapter\n", encoding="utf-8")
            findings = gates.engine_findings([adapter, ui, comment])
        self.assertEqual([(Path(path).name, line) for path, line, _ in findings], [("Screen.kt", 2)])

    def test_repository_has_no_engine_types_outside_adapters(self):
        self.assertEqual(gates.engine_findings(gates.source_files()), [])


class BrandTest(unittest.TestCase):
    def test_finds_candy_in_text_not_in_names(self):
        xml = """<resources>
            <string name="candy_trail_empty">Nothing here yet</string>
            <string name="about">About Candy Browser</string>
            <plurals name="tabs"><item quantity="one">%d Candy tab</item></plurals>
            <string name="ok">Candyfloss is fine</string>
        </resources>"""
        self.assertEqual(gates.brand_findings_in_xml(xml), ["about", "%d Candy tab"])

    def kotlin(self, text):
        return [line for _, line, _ in gates.brand_findings_in_kotlin(text, "Ui.kt")]

    def test_kotlin_literals_the_user_sees_are_findings(self):
        cases = [
            'Text(\n    text = "candy://gestures",\n)',
            'val title = "Welcome to Candy"',
            'label = { Text("Candy tabs") }',
            'error = if (failed) "Candy could not start" else null',
            "val script = \"\"\"\n    alert('Candy says hi');\n\"\"\"",
        ]
        for kotlin in cases:
            with self.subTest(kotlin=kotlin):
                self.assertEqual(len(self.kotlin(kotlin)), 1)
        self.assertEqual(self.kotlin('val a = 1\nText(\n    "Candy"\n)'), [3])

    def test_kotlin_names_logs_exceptions_and_exemptions_are_clean(self):
        cases = [
            "// Candy wrote this screen",
            '/** A "Candy" comment. */',
            'Log.e(TAG, "Candy rule snapshot could not be persisted")',
            'private const val TAG = "Candy"',
            'throw IllegalStateException("Candy host timed out")',
            'fail(IllegalStateException("Candy Privacy host disconnected"))',
            'require(ok) {\n    "Unsupported bundled Candy Rule"\n}',
            'check(ready) { "Candy is not ready" }',
            'Modifier.testTag("Candy tab")',
            'DiagnosticsStart("Candy.Diagnostics.Start")',
            'label = "Candy-Trail-Navigation"',
            'const val ACTION = "dev.sk2andy.materialbrowser.candy_open_tab"',
            'const val UPSTREAM = "Candy Browser" // brand-exempt: credit to the upstream project',
            '// brand-exempt: a protocol reason, never shown\nsocket.close(1002, "Invalid Candy Sync event")',
            "val script = \"\"\"\n    // Never during a Candy layout write.\n    begin('Candy.SafeArea.Reconcile');\n\"\"\"",
            'val name = "Candyfloss"',
        ]
        for kotlin in cases:
            with self.subTest(kotlin=kotlin):
                self.assertEqual(self.kotlin(kotlin), [])

    def test_repository_has_no_candy(self):
        self.assertEqual(gates.check_brand(), [])


class SemanticsTest(unittest.TestCase):
    def findings(self, kotlin):
        return [(line, message.split(" ")[0]) for _, line, message in
                gates.semantics_findings_in_text(kotlin, "Ui.kt")]

    def test_clearing_switched_by_a_condition_is_a_finding(self):
        cases = [
            "val m = Modifier.then(if (on) Modifier else Modifier.clearAndSetSemantics { })",
            "val m = if (dragged) {\n    Modifier.clearAndSetSemantics { }\n} else {\n    Modifier.semantics { }\n}",
            "fun Modifier.hide(b: Boolean) = if (b) clearAndSetSemantics { } else this",
            "fun Modifier.block(b: Boolean) = if (!b) {\n    this\n} else {\n    this\n        .clearAndSetSemantics { }\n}",
            "val m = Modifier.then(\n    if (a ||\n        b\n    ) {\n        Modifier.clearAndSetSemantics { }\n    } else {\n        Modifier\n    },\n)",
        ]
        for kotlin in cases:
            with self.subTest(kotlin=kotlin):
                self.assertEqual([kind for _, kind in self.findings(kotlin)], ["clearAndSetSemantics"])

    def test_steady_clearing_and_the_stable_helper_are_not(self):
        cases = [
            "val m = Modifier.padding(4.dp).clearAndSetSemantics { contentDescription = label }",
            "val m = if (empty) Modifier.clearAndSetSemantics { } else Modifier.clearAndSetSemantics { selected = true }",
            "val m = Modifier.clearSemanticsWhen(hidden)",
            "val size = if (big) 2 else 1\nval m = Modifier.clearAndSetSemantics { }",
            "Box(Modifier.size(if (big) 2.dp else 1.dp), modifier = Modifier.clearAndSetSemantics { })",
            "// semantics-exempt: fixed for the card's life\nval m = Modifier.then(if (row) Modifier.clearAndSetSemantics { } else Modifier)",
            "import androidx.compose.ui.semantics.clearAndSetSemantics",
            'val text = "if (x) clearAndSetSemantics { }" // if clearAndSetSemantics { }',
        ]
        for kotlin in cases:
            with self.subTest(kotlin=kotlin):
                self.assertEqual(self.findings(kotlin), [])

    def test_a_test_tag_after_clearing_in_the_same_chain_is_a_finding(self):
        hidden = "val m = Modifier\n    .clearAndSetSemantics { }\n    .padding(2.dp)\n    .testTag(\"title\")"
        self.assertEqual(self.findings(hidden), [(4, "testTag")])
        through_then = "val m = Modifier.then(Modifier.clearAndSetSemantics { }).testTag(\"x\")"
        self.assertEqual(self.findings(through_then), [(1, "testTag")])
        before = "val m = Modifier\n    .testTag(\"title\")\n    .clearAndSetSemantics { }"
        self.assertEqual(self.findings(before), [])
        other_statement = "val a = Modifier.clearAndSetSemantics { }\nval b = Modifier.testTag(\"x\")"
        self.assertEqual(self.findings(other_statement), [])

    def test_repository_has_no_findings(self):
        self.assertEqual(gates.semantics_findings(gates.source_files()), [])


if __name__ == "__main__":
    unittest.main()
